// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReformaTributaria.Infra.Context;

#nullable disable

namespace ReformaTributaria.Infra.Migrations
{
    [DbContext(typeof(ReformaTributariaDbContext))]
    [Migration("20260106194644_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReformaTributaria.Domain.Entities.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ChavePrivada")
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("InscricaoFederal")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("QuestorId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_clientes_ativo");

                    b.HasIndex("InscricaoFederal")
                        .IsUnique()
                        .HasDatabaseName("ix_clientes_inscricao_federal");

                    b.HasIndex("QuestorId")
                        .IsUnique()
                        .HasDatabaseName("ix_clientes_questor_id");

                    b.ToTable("clientes", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
