// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReformaTributaria.Infra.Context;

#nullable disable

namespace ReformaTributaria.Infra.Migrations
{
    [DbContext(typeof(ReformaTributariaDbContext))]
    [Migration("20260108133131_2322271_1")]
    partial class _2322271_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReformaTributaria.Domain.Entities.ApuracaoExecucaoCBS", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DataHoraRetornoTicketArquivo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataHoraSolicitacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("FilaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Mensagem")
                        .HasColumnType("text");

                    b.Property<string>("Tiquete")
                        .HasColumnType("text");

                    b.Property<string>("TiqueteArquivo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FilaId");

                    b.ToTable("ApuracaoExecucaoCBS", "public");
                });

            modelBuilder.Entity("ReformaTributaria.Domain.Entities.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ChavePrivada")
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("InscricaoFederal")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("QuestorId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("InscricaoFederal")
                        .IsUnique()
                        .HasDatabaseName("ix_clientes_inscricao_federal");

                    b.HasIndex("QuestorId")
                        .IsUnique()
                        .HasDatabaseName("ix_clientes_questor_id");

                    b.ToTable("Clientes", "public");
                });

            modelBuilder.Entity("ReformaTributaria.Domain.Entities.Fila", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataHoraInserção")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InscricaoFederalContribuinte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Filas", "public");
                });

            modelBuilder.Entity("ReformaTributaria.Domain.Entities.ApuracaoExecucaoCBS", b =>
                {
                    b.HasOne("ReformaTributaria.Domain.Entities.Fila", null)
                        .WithMany("ApuracoesExecucaoCBS")
                        .HasForeignKey("FilaId");
                });

            modelBuilder.Entity("ReformaTributaria.Domain.Entities.Fila", b =>
                {
                    b.HasOne("ReformaTributaria.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ReformaTributaria.Domain.Entities.Fila", b =>
                {
                    b.Navigation("ApuracoesExecucaoCBS");
                });
#pragma warning restore 612, 618
        }
    }
}
